# Generated by Django 5.0.1 on 2024-07-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='passowrd',
            new_name='password',
        ),
    ]
