# Generated by Django 5.0.7 on 2024-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_passowrd_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('exercise_name', models.CharField(max_length=64)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
            ],
        ),
    ]
